### PR TITLE
update gitignore, fix notebooks lines

### PR DESCRIPTION
**Pull request by alpers**
- exclamation mark was added to ln[4] in model_inference_demo.ipynb
- outputs were different then updated by running code
- gitignore was updated as @searchivarius said

### CODE REVIEW

**Comment by searchivarius** [comment]
Thanks a lot! On a second thought, we could also add all the other Java jars and related scripts to the repository and this will save building time. But it's a bit tricky due to the way app assembler works so this can be postponed.

**Comment by alpers** [comment]
> Thanks a lot! On a second thought, we could also add all the other Java jars and related scripts to the repository and this will save building time. But it's a bit tricky due to the way app assembler works so this can be postponed.

Thank you for your interest, this is great motivation for me :)
I am trying to run, test and develop the project. Which branch should i use for the latest and stable code, **master** or **repr2020-12-06**?

**Comment by searchivarius** [comment]
``repr2020-12-06`` is a snapshot to fully reproduce our non-neural run. 

I guess master should be fine too, buuut there might be some subtle difference. That said, there is going to be a sort of stable version within a couple of months, which will include some extra features.

**Comment by searchivarius** [comment]
PS: one issue is that we got stuck with a really old version of the Transformers library (for various reasons). And this is definitely gonna change, but we might keep using the old version in parallel, b/c it has a better support for gradient checkpointing.

**Comment by searchivarius** [comment]
PPS: ohh @alpers in terms of working on the code. A heads-up I am working on changing internal Java API a little bit right now, but then it's going to be largely frozen (at least for a while).

**Pull request merged**
